// Code generated by protoc-gen-go. DO NOT EDIT.
// source: project/project.proto

package project

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Project struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId               uint64               `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf0ca921a221351, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Project) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateProjectRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf0ca921a221351, []int{1}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf0ca921a221351, []int{2}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type FindProjectRequest struct {
	ProjectId            uint64   `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindProjectRequest) Reset()         { *m = FindProjectRequest{} }
func (m *FindProjectRequest) String() string { return proto.CompactTextString(m) }
func (*FindProjectRequest) ProtoMessage()    {}
func (*FindProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf0ca921a221351, []int{3}
}

func (m *FindProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindProjectRequest.Unmarshal(m, b)
}
func (m *FindProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindProjectRequest.Marshal(b, m, deterministic)
}
func (m *FindProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindProjectRequest.Merge(m, src)
}
func (m *FindProjectRequest) XXX_Size() int {
	return xxx_messageInfo_FindProjectRequest.Size(m)
}
func (m *FindProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindProjectRequest proto.InternalMessageInfo

func (m *FindProjectRequest) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

type FindProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindProjectResponse) Reset()         { *m = FindProjectResponse{} }
func (m *FindProjectResponse) String() string { return proto.CompactTextString(m) }
func (*FindProjectResponse) ProtoMessage()    {}
func (*FindProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf0ca921a221351, []int{4}
}

func (m *FindProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindProjectResponse.Unmarshal(m, b)
}
func (m *FindProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindProjectResponse.Marshal(b, m, deterministic)
}
func (m *FindProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindProjectResponse.Merge(m, src)
}
func (m *FindProjectResponse) XXX_Size() int {
	return xxx_messageInfo_FindProjectResponse.Size(m)
}
func (m *FindProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindProjectResponse proto.InternalMessageInfo

func (m *FindProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type FindProjectsResponse struct {
	Projects             []*Project `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindProjectsResponse) Reset()         { *m = FindProjectsResponse{} }
func (m *FindProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*FindProjectsResponse) ProtoMessage()    {}
func (*FindProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf0ca921a221351, []int{5}
}

func (m *FindProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindProjectsResponse.Unmarshal(m, b)
}
func (m *FindProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindProjectsResponse.Marshal(b, m, deterministic)
}
func (m *FindProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindProjectsResponse.Merge(m, src)
}
func (m *FindProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_FindProjectsResponse.Size(m)
}
func (m *FindProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindProjectsResponse proto.InternalMessageInfo

func (m *FindProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type UpdateProjectRequest struct {
	ProjectId            uint64   `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName          string   `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectRequest) Reset()         { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()    {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf0ca921a221351, []int{6}
}

func (m *UpdateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectRequest.Unmarshal(m, b)
}
func (m *UpdateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectRequest.Merge(m, src)
}
func (m *UpdateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectRequest.Size(m)
}
func (m *UpdateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectRequest proto.InternalMessageInfo

func (m *UpdateProjectRequest) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *UpdateProjectRequest) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type UpdateProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectResponse) Reset()         { *m = UpdateProjectResponse{} }
func (m *UpdateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectResponse) ProtoMessage()    {}
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cf0ca921a221351, []int{7}
}

func (m *UpdateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectResponse.Unmarshal(m, b)
}
func (m *UpdateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectResponse.Merge(m, src)
}
func (m *UpdateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectResponse.Size(m)
}
func (m *UpdateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectResponse proto.InternalMessageInfo

func (m *UpdateProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func init() {
	proto.RegisterType((*Project)(nil), "project.Project")
	proto.RegisterType((*CreateProjectRequest)(nil), "project.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "project.CreateProjectResponse")
	proto.RegisterType((*FindProjectRequest)(nil), "project.FindProjectRequest")
	proto.RegisterType((*FindProjectResponse)(nil), "project.FindProjectResponse")
	proto.RegisterType((*FindProjectsResponse)(nil), "project.FindProjectsResponse")
	proto.RegisterType((*UpdateProjectRequest)(nil), "project.UpdateProjectRequest")
	proto.RegisterType((*UpdateProjectResponse)(nil), "project.UpdateProjectResponse")
}

func init() { proto.RegisterFile("project/project.proto", fileDescriptor_2cf0ca921a221351) }

var fileDescriptor_2cf0ca921a221351 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x41, 0xaf, 0x93, 0x40,
	0x10, 0x0e, 0xbc, 0xe6, 0xd5, 0x0e, 0xef, 0x35, 0x66, 0x6d, 0x95, 0x50, 0xab, 0xc8, 0xa9, 0x69,
	0x14, 0x0c, 0x3d, 0x79, 0xac, 0xb5, 0xc6, 0x5e, 0x9a, 0x06, 0x35, 0x31, 0x5e, 0x1a, 0x60, 0x57,
	0xc4, 0x96, 0x2e, 0xb2, 0x8b, 0xc6, 0xa3, 0x3f, 0xcd, 0x7f, 0x66, 0x0a, 0xbb, 0x94, 0x52, 0x34,
	0xd1, 0x13, 0xcc, 0xcc, 0xb7, 0xdf, 0xcc, 0x7c, 0x1f, 0x0b, 0x0c, 0xd3, 0x8c, 0x7e, 0x21, 0x21,
	0x77, 0xc4, 0xd3, 0x4e, 0x33, 0xca, 0x29, 0xea, 0x8a, 0xd0, 0x78, 0x1c, 0x51, 0x1a, 0xed, 0x89,
	0x53, 0xa4, 0x83, 0xfc, 0x93, 0xc3, 0xe3, 0x84, 0x30, 0xee, 0x27, 0x69, 0x89, 0x34, 0x46, 0x4d,
	0x00, 0x49, 0x52, 0xfe, 0xa3, 0x2c, 0x5a, 0x3f, 0x15, 0xe8, 0x6e, 0x4a, 0x26, 0xd4, 0x07, 0x35,
	0xc6, 0xba, 0x62, 0x2a, 0x93, 0x8e, 0xa7, 0xc6, 0x18, 0x21, 0xe8, 0x1c, 0xfc, 0x84, 0xe8, 0xaa,
	0xa9, 0x4c, 0x7a, 0x5e, 0xf1, 0x8e, 0x1e, 0x40, 0x37, 0x67, 0x24, 0xdb, 0xc6, 0x58, 0xbf, 0x2a,
	0x80, 0xd7, 0xc7, 0x70, 0x85, 0xd1, 0x0b, 0x80, 0x30, 0x23, 0x3e, 0x27, 0x78, 0xeb, 0x73, 0xbd,
	0x63, 0x2a, 0x13, 0xcd, 0x35, 0xec, 0xb2, 0xb5, 0x2d, 0x5b, 0xdb, 0xef, 0xe4, 0x6c, 0x5e, 0x4f,
	0xa0, 0xe7, 0xdc, 0x9a, 0xc2, 0x60, 0x51, 0x04, 0x62, 0x10, 0x8f, 0x7c, 0xcd, 0x09, 0xe3, 0x55,
	0x7f, 0xe5, 0xd4, 0xdf, 0x5a, 0xc0, 0xb0, 0x81, 0x65, 0x29, 0x3d, 0x30, 0x82, 0xa6, 0x20, 0x15,
	0x29, 0xf0, 0x9a, 0x7b, 0xd7, 0x96, 0x82, 0x49, 0xa8, 0x04, 0x58, 0x33, 0x40, 0xaf, 0xe3, 0x03,
	0x6e, 0xb4, 0x1b, 0x03, 0x08, 0xc0, 0xb6, 0x92, 0xa1, 0x27, 0x32, 0x2b, 0x6c, 0xcd, 0xe1, 0xde,
	0xd9, 0xa1, 0xff, 0xe8, 0xfb, 0x0a, 0x06, 0x35, 0x0a, 0x56, 0x71, 0x3c, 0x85, 0x3b, 0x02, 0xc2,
	0x74, 0xd5, 0xbc, 0x6a, 0x25, 0xa9, 0x10, 0xd6, 0x07, 0x18, 0xbc, 0x4f, 0xf1, 0xa5, 0x5c, 0x7f,
	0x9f, 0x1f, 0x3d, 0x81, 0x1b, 0x59, 0xae, 0xb9, 0xaa, 0x89, 0xdc, 0x5a, 0x88, 0xdb, 0x60, 0xfe,
	0xf7, 0x25, 0xdd, 0x5f, 0x2a, 0xf4, 0x45, 0xf2, 0x2d, 0xc9, 0xbe, 0xc5, 0x21, 0x41, 0x6b, 0xb8,
	0x3d, 0x33, 0x0d, 0x8d, 0xab, 0xe3, 0x6d, 0xc6, 0x1b, 0x8f, 0xfe, 0x54, 0x16, 0xe3, 0xbc, 0x01,
	0xad, 0xa6, 0x23, 0x1a, 0x55, 0xf0, 0x4b, 0x57, 0x8d, 0x87, 0xed, 0x45, 0xc1, 0xb4, 0x84, 0x9b,
	0xba, 0x23, 0xe8, 0xfe, 0xc5, 0x17, 0xbb, 0x3c, 0x5e, 0x16, 0x63, 0xdc, 0xc6, 0x72, 0x32, 0x70,
	0x0d, 0xb7, 0x67, 0xc2, 0xd5, 0x16, 0x6c, 0xb3, 0xaa, 0xb6, 0x60, 0xab, 0xde, 0x2f, 0xdd, 0x8f,
	0xcf, 0xa3, 0x98, 0x7f, 0xce, 0x03, 0x3b, 0xa4, 0x89, 0x13, 0xd0, 0x5d, 0xfe, 0xdd, 0xdf, 0xe5,
	0x89, 0xef, 0x44, 0xde, 0x66, 0xf1, 0x8c, 0xf9, 0x49, 0xba, 0x27, 0xac, 0xbc, 0xd0, 0xf2, 0xb7,
	0x10, 0x5c, 0x17, 0xe1, 0xec, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xd7, 0x23, 0xdb, 0x30,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectServiceClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error)
	FindProject(ctx context.Context, in *FindProjectRequest, opts ...grpc.CallOption) (*FindProjectResponse, error)
	FindProjects(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FindProjectsResponse, error)
	UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error)
}

type projectServiceClient struct {
	cc *grpc.ClientConn
}

func NewProjectServiceClient(cc *grpc.ClientConn) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*CreateProjectResponse, error) {
	out := new(CreateProjectResponse)
	err := c.cc.Invoke(ctx, "/project.ProjectService/CreateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) FindProject(ctx context.Context, in *FindProjectRequest, opts ...grpc.CallOption) (*FindProjectResponse, error) {
	out := new(FindProjectResponse)
	err := c.cc.Invoke(ctx, "/project.ProjectService/FindProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) FindProjects(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FindProjectsResponse, error) {
	out := new(FindProjectsResponse)
	err := c.cc.Invoke(ctx, "/project.ProjectService/FindProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...grpc.CallOption) (*UpdateProjectResponse, error) {
	out := new(UpdateProjectResponse)
	err := c.cc.Invoke(ctx, "/project.ProjectService/UpdateProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
type ProjectServiceServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*CreateProjectResponse, error)
	FindProject(context.Context, *FindProjectRequest) (*FindProjectResponse, error)
	FindProjects(context.Context, *empty.Empty) (*FindProjectsResponse, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*UpdateProjectResponse, error)
}

// UnimplementedProjectServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProjectServiceServer struct {
}

func (*UnimplementedProjectServiceServer) CreateProject(ctx context.Context, req *CreateProjectRequest) (*CreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProject not implemented")
}
func (*UnimplementedProjectServiceServer) FindProject(ctx context.Context, req *FindProjectRequest) (*FindProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProject not implemented")
}
func (*UnimplementedProjectServiceServer) FindProjects(ctx context.Context, req *empty.Empty) (*FindProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProjects not implemented")
}
func (*UnimplementedProjectServiceServer) UpdateProject(ctx context.Context, req *UpdateProjectRequest) (*UpdateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProject not implemented")
}

func RegisterProjectServiceServer(s *grpc.Server, srv ProjectServiceServer) {
	s.RegisterService(&_ProjectService_serviceDesc, srv)
}

func _ProjectService_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_FindProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).FindProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/FindProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).FindProject(ctx, req.(*FindProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_FindProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).FindProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/FindProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).FindProjects(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/project.ProjectService/UpdateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).UpdateProject(ctx, req.(*UpdateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "project.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _ProjectService_CreateProject_Handler,
		},
		{
			MethodName: "FindProject",
			Handler:    _ProjectService_FindProject_Handler,
		},
		{
			MethodName: "FindProjects",
			Handler:    _ProjectService_FindProjects_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _ProjectService_UpdateProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "project/project.proto",
}
